const lessonTitle = "大荣姨";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "Saya"],
    ["记事以来", "jì shì yǐ lái", "since I can remember", "sejak saya ingat"],
    ["的", "de", "", ""],
    ["第一个朋友", "dì yī gè péng yǒu", "first friend", "kawan pertama"],
    ["，", "", "", ""],
    ["是", "shì", "was", "ialah"],
    ["保姆奶奶", "bǎo mǔ nǎi nai", "nanny grandma", "nenek pengasuh"],
    ["的", "de", "", ""],
    ["一位邻居", "yí wèi lín jū", "a neighbour", "seorang jiran"],
    ["，", "", "", ""],
    ["我叫她", "wǒ jiào tā", "I called her", "saya panggil dia"],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["那时候", "nà shí hou", "At that time", "Pada masa itu"],
    ["我", "wǒ", "I", "saya"],
    ["三岁", "sān suì", "three years old", "tiga tahun"],
    ["，", "", "", ""],
    ["生活", "shēng huó", "lived", "tinggal"],
    ["在", "zài", "in", "di"],
    ["北京", "běi jīng", "Beijing", "Beijing"],
    ["。", "", "", ""],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["是", "shì", "was", "ialah"],
    ["个", "ge", "a", "seorang"],
    ["中学生", "zhōng xué shēng", "middle school student", "pelajar menengah"],
    ["，", "", "", ""],
    ["有", "yǒu", "had", "mempunyai"],
    ["一张", "yì zhāng", "a", "sehelai"],
    ["圆脸", "yuán liǎn", "round face", "muka bulat"],
    ["，", "", "", ""],
    ["两只", "liǎng zhī", "two", "sepasang"],
    ["细长眼睛", "xì cháng yǎn jīng", "slender eyes", "mata yang nipis dan panjang"],
    ["，", "", "", ""],
    ["鼻梁两侧", "bí liáng liǎng cè", "on both sides of the nose bridge", "di kedua-dua sisi batang hidung"],
    ["生些", "shēng xiē", "had some", "ada beberapa"],
    ["雀斑", "què bān", "freckles", "bintik-bintik"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["不讨厌她", "bù tǎo yàn tā", "didn't dislike her", "tidak benci dia"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["也", "yě", "also", "juga"],
    ["特别", "tè bié", "especially", "sangat"],
    ["喜欢", "xǐ huān", "liked", "suka"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["经常", "jīng cháng", "often", "sering"],
    ["在", "zài", "at", "pada"],
    ["中午", "zhōng wǔ", "noon", "tengah hari"],
    ["来到", "lái dào", "came to", "datang ke"],
    ["保姆奶奶家", "bǎo mǔ nǎi nai jiā", "nanny grandma's house", "rumah nenek pengasuh"],
    ["，", "", "", ""],
    ["自愿", "zì yuàn", "voluntarily", "secara sukarela"],
    ["哄我睡午觉", "hǒng wǒ shuì wǔ jiào", "put me to nap", "menidurkan saya tidur tengah hari"],
    ["，", "", "", ""],
    ["一边", "yì biān", "while", "sambil"],
    ["给我讲些", "gěi wǒ jiǎng xiē", "tell me some", "bercerita beberapa"],
    ["啰嗦而又漫长的故事", "luō suo ér yòu màn cháng de gù shì", "long-winded and lengthy stories", "cerita yang berjela-jela dan panjang"],
    ["，", "", "", ""],
    ["也不管我", "yě bù guǎn wǒ", "regardless of whether I", "tidak peduli saya"],
    ["是否听得懂", "shì fǒu tīng de dǒng", "could understand", "faham atau tidak"],
    ["。", "", "", ""],
    ["那些故事", "nà xiē gù shì", "Those stories", "Cerita-cerita itu"],
    ["我都遗忘了", "wǒ dōu yí wàng le", "I have all forgotten", "saya semua telah lupa"],
    ["，", "", "", ""],
    ["至今", "zhì jīn", "until now", "sehingga kini"],
    ["只记得", "zhǐ jì de", "only remember", "hanya ingat"],
    ["有个故事", "yǒu ge gù shì", "there was a story", "ada sebuah cerita"],
    ["中的一句话", "zhōng de yí jù huà", "one sentence", "satu ayat di dalamnya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["他走到了", "tā zǒu dào le", "He walked to", "Dia berjalan ke"],
    ["一个十字路口", "yí gè shí zì lù kǒu", "a crossroads", "persimpangan jalan"],
    ["......”", "", "", ""],
    ["什么叫", "shén me jiào", "What does", "Apa maksud"],
    ["“", "", "", ""],
    ["狮子路口", "shī zi lù kǒu", "lion road", "jalan singa"],
    ["”", "", "", ""],
    ["呀", "ya", "", ""],
    ["？", "", "", ""],
    ["三岁的我", "sān suì de wǒ", "Three-year-old me", "Saya yang berusia tiga tahun"],
    ["竭力猜测着", "jié lì cāi cè zhe", "tried hard to guess", "berusaha keras meneka"],
    ["：", "", "", ""],
    ["一定", "yí dìng", "must be", "pasti"],
    ["是", "shì", "is", "ialah"],
    ["那个路口", "nà ge lù kǒu", "that intersection", "persimpangan itu"],
    ["有狮子", "yǒu shī zi", "has a lion", "ada seekor singa"],
    ["。", "", "", ""],
    ["狮子", "shī zi", "Lions", "Singa"],
    ["我是见过的", "wǒ shì jiàn guò de", "I had seen", "saya pernah melihat"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["父母", "fù mǔ", "my parents", "ibu bapa"],
    ["抱我", "bào wǒ", "carried me", "mendukung saya"],
    ["去过", "qù guò", "had taken me to", "pernah pergi ke"],
    ["动物园的", "dòng wù yuán de", "zoo's", "kebun binatang punya"],
    ["狮虎山", "shī hǔ shān", "Lion and Tiger Hill", "Bukit Singa dan Harimau"],
    ["。", "", "", ""],
    ["但", "dàn", "But", "Tetapi"],
    ["我", "wǒ", "I", "saya"],
    ["从未", "cóng wèi", "never", "tidak pernah"],
    ["向大荣姨", "xiàng dà róng yí", "asked Da Rong Yi", "bertanya kepada Makcik Da Rong"],
    ["证实过", "zhèng shí guò", "confirmed", "mengesahkan"],
    ["我的猜测", "wǒ de cāi cè", "my guess", "tekaan saya"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["每当", "měi dāng", "whenever", "setiap kali"],
    ["她讲到", "tā jiǎng dào", "she said", "dia berkata"],
    ["“", "", "", ""],
    ["十字路口", "shí zì lù kǒu", "crossroads", "persimpangan"],
    ["”", "", "", ""],
    ["时", "shí", "when", "ketika"],
    ["，", "", "", ""],
    ["我就快睡着了", "wǒ jiù kuài shuì zháo le", "I would fall asleep", "saya akan tertidur"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["我", "wǒ", "I", "Saya"],
    ["弄懂", "nòng dǒng", "understood", "faham"],
    ["“", "", "", ""],
    ["十字路口", "shí zì lù kǒu", "crossroads", "persimpangan"],
    ["”", "", "", ""],
    ["这个词", "zhè ge cí", "this word", "perkataan ini"],
    ["的含义", "de hán yì", "meaning", "makna"],
    ["是", "shì", "was", "ialah"],
    ["念小学以后的事", "niàn xiǎo xué yǐ hòu de shì", "after starting primary school", "selepas masuk sekolah rendah"],
    ["。", "", "", ""],
    ["这时", "zhè shí", "By then", "Pada masa itu"],
    ["，", "", "", ""],
    ["我已", "wǒ yǐ", "I had", "saya sudah"],
    ["随父母", "suí fù mǔ", "with my parents", "bersama ibu bapa"],
    ["离开了北京", "lí kāi le běi jīng", "left Beijing", "meninggalkan Beijing"],
    ["，", "", "", ""],
    ["离开了", "lí kāi le", "left", "meninggalkan"],
    ["我的保姆奶奶", "wǒ de bǎo mǔ nǎi nai", "my nanny grandma", "nenek pengasuh saya"],
    ["和", "hé", "and", "dan"],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["小学二年级", "xiǎo xué èr nián jí", "Second grade of primary school", "Tahun dua sekolah rendah"],
    ["的", "de", "", ""],
    ["暑假里", "shǔ jià lǐ", "during summer vacation", "semasa cuti musim panas"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["去北京", "qù běi jīng", "went to Beijing", "pergi ke Beijing"],
    ["看望了", "kàn wàng le", "visited", "melawat"],
    ["保姆奶奶", "bǎo mǔ nǎi nai", "nanny grandma", "nenek pengasuh"],
    ["和", "hé", "and", "dan"],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["。", "", "", ""],
    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["添了不少", "tiān le bù shǎo", "had added a lot of", "bertambah banyak"],
    ["白头发", "bái tóu fa", "white hair", "rambut putih"],
    ["，", "", "", ""],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["是", "shì", "was", "ialah"],
    ["个地道的", "ge dì dào de", "a proper", "seorang yang betul-betul"],
    ["大人了", "dà rén le", "grown-up", "dewasa"],
    ["，", "", "", ""],
    ["在", "zài", "at", "di"],
    ["副食店里", "fù shí diàn lǐ", "in a grocery store", "di kedai runcit"],
    ["卖酱油", "mài jiàng yóu", "selling soy sauce", "menjual kicap"],
    ["——", "", "", ""],
    ["这使我", "zhè shǐ wǒ", "this made me", "ini membuatkan saya"],
    ["略微有点失望", "lüè wēi yǒu diǎn shī wàng", "slightly disappointed", "sedikit kecewa"],
    ["。", "", "", ""],
    ["我总以为", "wǒ zǒng yǐ wéi", "I always thought", "saya selalu fikir"],
    ["，", "", "", ""],
    ["一个会讲", "yí gè huì jiǎng", "someone who could tell", "seorang yang boleh bercerita"],
    ["“", "", "", ""],
    ["十字路口", "shí zì lù kǒu", "crossroads", "persimpangan"],
    ["”", "", "", ""],
    ["的人", "de rén", "person", "orang"],
    ["不一定", "bù yí dìng", "shouldn't necessarily", "tidak semestinya"],
    ["非卖酱油不可", "fēi mài jiàng yóu bù kě", "sell soy sauce", "menjual kicap"],
    ["。", "", "", ""],
    ["但是", "dàn shì", "But", "Tetapi"],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["却", "què", "however", "sebaliknya"],
    ["像从前一样快乐", "xiàng cóng qián yí yàng kuài lè", "as happy as before", "seriang dulu"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["和奶奶", "hé nǎi nai", "and Grandma", "dan nenek"],
    ["去她家时", "qù tā jiā shí", "when we went to her house", "apabila kami pergi ke rumahnya"],
    ["，", "", "", ""],
    ["见她正坐在", "jiàn tā zhèng zuò zài", "saw her sitting", "nampak dia sedang duduk di"],
    ["一只", "yì zhī", "a", "sebuah"],
    ["马扎上", "mǎ zhā shàng", "camp stool", "kerusi lipat"],
    ["编网兜", "biān wǎng dōu", "knitting a net bag", "menganyam beg jaring"],
    ["，", "", "", ""],
    ["用", "yòng", "using", "menggunakan"],
    ["红色透明的", "hóng sè tòu míng de", "red transparent", "merah telus"],
    ["玻璃丝", "bō li sī", "glass silk", "benang kaca"],
    ["。", "", "", ""],
    ["她问我", "tā wèn wǒ", "She asked me", "Dia bertanya saya"],
    ["喜欢不喜欢", "xǐ huān bù xǐ huān", "if I liked", "suka atau tidak"],
    ["这种网兜", "zhè zhǒng wǎng dōu", "this kind of net bag", "beg jaring jenis ini"],
    ["，", "", "", ""],
    ["并告诉我", "bìng gào su wǒ", "and told me", "dan memberitahu saya"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["专门", "zhuān mén", "specially", "khas"],
    ["装语录本用的", "zhuāng yǔ lù běn yòng de", "for holding a quotation book", "untuk menyimpan buku petikan"],
    ["。", "", "", ""],
    ["北京的", "běi jīng de", "Beijing's", "Beijing punya"],
    ["女孩子", "nǚ hái zi", "girls", "gadis-gadis"],
    ["，", "", "", ""],
    ["很多人", "hěn duō rén", "many people", "ramai orang"],
    ["都在为", "dōu zài wèi", "were all", "semua sedang"],
    ["语录本", "yǔ lù běn", "quotation book", "buku petikan"],
    ["编织小网兜", "biān zhī xiǎo wǎng dōu", "knitting small net bags", "menganyam beg jaring kecil"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["斜背在身上", "xié bēi zài shēn shàng", "worn diagonally", "disandang di badan"],
    ["，", "", "", ""],
    ["或游行", "huò yóu xíng", "either in parades", "sama ada dalam perarakan"],
    ["，", "", "", ""],
    ["或开会", "huò kāi huì", "or at meetings", "atau dalam mesyuarat"],
    ["，", "", "", ""],
    ["很帅", "hěn shuài", "very stylish", "sangat bergaya"],
    ["，", "", "", ""],
    ["正时兴呢", "zhèng shí xīng ne", "quite fashionable", "sedang menjadi trend"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["我也拥有", "wǒ yě yōng yǒu", "I also had", "Saya juga mempunyai"],
    ["巴掌大", "bā zhǎng dà", "palm-sized", "sebesar tapak tangan"],
    ["的一本", "de yì běn", "a", "sebatang"],
    ["语录", "yǔ lù", "quotation book", "buku petikan"],
    ["，", "", "", ""],
    ["觉得", "jué de", "felt", "merasa"],
    ["若是", "ruò shì", "if", "jika"],
    ["配以", "pèi yǐ", "paired with", "dipadankan dengan"],
    ["红玻璃丝", "hóng bō li sī", "red glass silk", "benang kaca merah"],
    ["网兜", "wǎng dōu", "net bag", "beg jaring"],
    ["背在肩上", "bēi zài jiān shàng", "worn on the shoulder", "disandang di bahu"],
    ["，", "", "", ""],
    ["一定", "yí dìng", "would surely", "pasti"],
    ["非比寻常", "fēi bǐ xún cháng", "extraordinary", "luar biasa"],
    ["。", "", "", ""],
    ["现在想来", "xiàn zài xiǎng lái", "Now when I think about it", "Sekarang difikirkan semula"],
    ["，", "", "", ""],
    ["我那时的", "wǒ nà shí de", "my at that time", "saya pada masa itu punya"],
    ["心态", "xīn tài", "mentality", "mentaliti"],
    ["，", "", "", ""],
    ["正如同", "zhèng rú tóng", "exactly like", "sama seperti"],
    ["今日", "jīn rì", "today's", "hari ini punya"],
    ["女孩子们", "nǚ hái zi men", "girls", "gadis-gadis"],
    ["渴盼", "kě pàn", "longing for", "mengharapkan"],
    ["一条新奇的", "yì tiáo xīn qí de", "a novel", "sehelai yang baharu"],
    ["裙子", "qún zi", "skirt", "skirt"],
    ["或", "huò", "or", "atau"],
    ["一双时髦的", "yì shuāng shí máo de", "a fashionable", "sepasang yang bergaya"],
    ["运动鞋", "yùn dòng xié", "sneakers", "kasut sukan"],
    ["那般焦灼了", "nà bān jiāo zhuó le", "anxious", "begitu cemas"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["请大荣姨", "qǐng dà róng yí", "asked Da Rong Yi", "minta Makcik Da Rong"],
    ["立刻", "lì kè", "immediately", "segera"],
    ["给我编一个", "gěi wǒ biān yí gè", "knit one for me", "anyamkan satu untuk saya"],
    ["小网兜", "xiǎo wǎng dōu", "small net bag", "beg jaring kecil"],
    ["，", "", "", ""],
    ["大荣姨却说", "dà róng yí què shuō", "but Da Rong Yi said", "tetapi Makcik Da Rong berkata"],
    ["编完手下这个", "biān wán shǒu xià zhè ge", "finish this one first", "selesaikan yang ini dulu"],
    ["才能给我编", "cái néng gěi wǒ biān", "then knit for me", "baru boleh anyam untuk saya"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["手下这个", "shǒu xià zhè ge", "this one", "yang ini"],
    ["也是", "yě shì", "also", "juga"],
    ["旁人求她的", "páng rén qiú tā de", "someone else asked for", "orang lain minta daripadanya"],
    ["，", "", "", ""],
    ["那求她的人", "nà qiú tā de rén", "the person who asked", "orang yang meminta itu"],
    ["就在", "jiù zài", "was just", "berada di"],
    ["她的家里", "tā de jiā lǐ", "in her home", "di rumahnya"],
    ["坐等", "zuò děng", "sitting and waiting", "duduk menunggu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["我", "wǒ", "I", "Saya"],
    ["环顾四周", "huán gù sì zhōu", "looked around", "memandang sekeliling"],
    ["，", "", "", ""],
    ["这才发现", "zhè cái fā xiàn", "only then discovered", "baru tersedar"],
    ["，", "", "", ""],
    ["在", "zài", "at", "di"],
    ["不远处", "bù yuǎn chù", "not far away", "tidak jauh"],
    ["的一张", "de yì zhāng", "a", "sebuah"],
    ["椅子上", "yǐ zi shàng", "chair", "kerusi"],
    ["，", "", "", ""],
    ["坐着", "zuò zhe", "sat", "duduk"],
    ["一位", "yí wèi", "a", "seorang"],
    ["和我年纪相仿的", "hé wǒ nián jì xiāng fǎng de", "girl about my age", "gadis sebaya saya"],
    ["女孩子", "nǚ hái zi", "girl", "gadis"],
    ["。", "", "", ""],
    ["大荣姨手中", "dà róng yí shǒu zhōng", "In Da Rong Yi's hands", "Di tangan Makcik Da Rong"],
    ["的", "de", "", ""],
    ["这件半成品", "zhè jiàn bàn chéng pǐn", "this half-finished piece", "barang separuh siap ini"],
    ["，", "", "", ""],
    ["便是她的了", "biàn shì tā de le", "was hers", "ialah miliknya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["这", "zhè", "This", "Ini"],
    ["使", "shǐ", "made", "membuatkan"],
    ["我", "wǒ", "me", "saya"],
    ["有点别扭", "yǒu diǎn biè niu", "a bit uncomfortable", "sedikit kekok"],
    ["。", "", "", ""],
    ["不知为什么", "bù zhī wèi shén me", "I don't know why", "Entah mengapa"],
    ["，", "", "", ""],
    ["此刻", "cǐ kè", "at this moment", "pada masa ini"],
    ["我", "wǒ", "I", "saya"],
    ["很想在", "hěn xiǎng zài", "really wanted to", "sangat mahu"],
    ["那个女孩子面前", "nà ge nǚ hái zi miàn qián", "in front of that girl", "di hadapan gadis itu"],
    ["显示", "xiǎn shì", "show", "menunjukkan"],
    ["我和大荣姨", "wǒ hé dà róng yí", "the closeness between me and Da Rong Yi", "hubungan rapat saya dan Makcik Da Rong"],
    ["之间的亲密", "zhī jiān de qīn mì", "", ""],
    ["，", "", "", ""],
    ["用现在的话讲", "yòng xiàn zài de huà jiǎng", "in today's words", "dalam kata-kata sekarang"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "that is", "iaitu"],
    ["显示我们的", "xiǎn shì wǒ men de", "show our", "menunjukkan"],
    ["“", "", "", ""],
    ["够哥们儿", "gòu gē men r", "close friendship", "persahabatan yang rapat"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["说", "shuō", "said", "berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["先给我编吧", "xiān gěi wǒ biān ba", "Knit for me first", "Anyam untuk saya dulu"],
    ["。”", "", "", ""],
    ["“", "", "", ""],
    ["那可不行", "nà kě bù xíng", "That won't do", "Itu tidak boleh"],
    ["。”", "", "", ""],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["头也不抬", "tóu yě bù tái", "without even looking up", "tanpa mendongak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["“", "", "", ""],
    ["为什么不行", "wèi shén me bù xíng", "Why not", "Kenapa tidak"],
    ["？”", "", "", ""],
    ["“", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["别人先求了我呀", "bié rén xiān qiú le wǒ ya", "someone else asked me first", "orang lain minta saya dulu"],
    ["。”", "", "", ""],
    ["“", "", "", ""],
    ["那你", "nà nǐ", "But you", "Tetapi awak"],
    ["还是", "hái shì", "are still", "masih"],
    ["我的大荣姨呢", "wǒ de dà róng yí ne", "my Da Rong Yi", "Makcik Da Rong saya"],
    ["。”", "", "", ""],
    ["“", "", "", ""],
    ["所以", "suǒ yǐ", "That's why", "Sebab itu"],
    ["不能", "bù néng", "cannot", "tidak boleh"],
    ["先给你编", "xiān gěi nǐ biān", "knit for you first", "anyam untuk awak dulu"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["“", "", "", ""],
    ["就得先给我编", "jiù déi xiān gěi wǒ biān", "Must knit for me first", "Mesti anyam untuk saya dulu"],
    ["。”", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["口气强硬起来", "kǒu qì qiáng yìng qǐ lái", "said firmly", "berkata dengan tegas"],
    ["，", "", "", ""],
    ["心里", "xīn lǐ", "in my heart", "dalam hati"],
    ["却", "què", "but", "tetapi"],
    ["忽然", "hū rán", "suddenly", "tiba-tiba"],
    ["有些", "yǒu xiē", "somewhat", "agak"],
    ["沉不住气", "chén bù zhù qì", "uneasy", "tidak sabar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["也有点", "yě yǒu diǎn", "also a bit", "juga agak"],
    ["冒火的样子", "mào huǒ de yàng zi", "looked angry", "kelihatan marah"],
    ["，", "", "", ""],
    ["又说了", "yòu shuō le", "said again", "berkata lagi"],
    ["一个", "yí gè", "a", "satu"],
    ["“", "", "", ""],
    ["不行", "bù xíng", "No", "Tidak"],
    ["”", "", "", ""],
    ["，", "", "", ""],
    ["就不再理我了", "jiù bù zài lǐ wǒ le", "and ignored me", "dan tidak mempedulikan saya lagi"],
    ["。", "", "", ""],
    ["看来", "kàn lái", "It seemed", "Nampaknya"],
    ["她是", "tā shì", "she", "dia"],
    ["真不打算", "zhēn bù dǎ suàn", "really didn't intend to", "benar-benar tidak berniat"],
    ["先给我编了", "xiān gěi wǒ biān le", "knit for me first", "anyam untuk saya dulu"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["这已", "zhè yǐ", "this was no longer", "ini sudah"],
    ["不是最重要的", "bú shì zuì zhòng yào de", "the most important thing", "bukan yang paling penting"],
    ["。", "", "", ""],
    ["重要的", "zhòng yào de", "What mattered", "Yang penting"],
    ["是", "shì", "was", "ialah"],
    ["这使我在", "zhè shǐ wǒ zài", "this made me", "ini membuatkan saya"],
    ["那个女孩子跟前", "nà ge nǚ hái zi gēn qián", "in front of that girl", "di hadapan gadis itu"],
    ["出了丑", "chū le chǒu", "embarrassed", "malu"],
    ["，", "", "", ""],
    ["这还算朋友么", "zhè hái suàn péng yǒu me", "how could this be a friend", "ini masih boleh kawan"],
    ["？", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["嘟嘟囔囔地", "dū dū nāng nāng de", "mumbling", "merungut"],
    ["出了大荣姨的家", "chū le dà róng yí de jiā", "left Da Rong Yi's house", "keluar dari rumah Makcik Da Rong"],
    ["，", "", "", ""],
    ["很有些", "hěn yǒu xiē", "quite", "agak"],
    ["悲愤欲绝", "bēi fèn yù jué", "indignant and heartbroken", "sangat marah dan kecewa"],
    ["，", "", "", ""],
    ["并一再想着", "bìng yī zài xiǎng zhe", "and kept thinking", "dan terus berfikir"],
    ["，", "", "", ""],
    ["其实", "qí shí", "actually", "sebenarnya"],
    ["那小网兜", "nà xiǎo wǎng dōu", "that little net bag", "beg jaring kecil itu"],
    ["用来装语录本", "yòng lái zhuāng yǔ lù běn", "used for the quotation book", "digunakan untuk buku petikan"],
    ["，", "", "", ""],
    ["也不一定好看", "yě bù yí dìng hǎo kàn", "might not even look good", "mungkin tidak cantik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["第二天早晨", "dì èr tiān zǎo chén", "The next morning", "Keesokan pagi"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["我", "wǒ", "I", "saya"],
    ["一觉醒来", "yī jiào xǐng lái", "woke up", "terjaga"],
    ["，", "", "", ""],
    ["发现", "fā xiàn", "discovered", "menemui"],
    ["枕边", "zhěn biān", "beside the pillow", "di sisi bantal"],
    ["有一只", "yǒu yì zhī", "there was a", "ada sehelai"],
    ["崭新的", "zhǎn xīn de", "brand new", "baharu"],
    ["玻璃丝网兜", "bō li sī wǎng dōu", "glass silk net bag", "beg jaring benang kaca"],
    ["，", "", "", ""],
    ["那网兜的大小", "nà wǎng dōu de dà xiǎo", "the size of the net bag", "saiz beg jaring itu"],
    ["，", "", "", ""],
    ["恰好", "qià hǎo", "just right", "betul-betul"],
    ["可装一本", "kě zhuāng yì běn", "could hold a", "boleh memuatkan sebatang"],
    ["四十八开的", "sì shí bā kāi de", "forty-eightmo", "saiz 48"],
    ["语录", "yǔ lù", "quotation book", "buku petikan"],
    ["。", "", "", ""],
    ["保姆奶奶", "bǎo mǔ nǎi nai", "Nanny grandma", "Nenek pengasuh"],
    ["告诉", "gào su", "told", "memberitahu"],
    ["我", "wǒ", "me", "saya"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this was", "ini adalah"],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["连夜", "lián yè", "through the night", "sepanjang malam"],
    ["给我编的", "gěi wǒ biān de", "knitted for me", "anyam untuk saya"],
    ["，", "", "", ""],
    ["早晨", "zǎo chén", "in the morning", "pagi"],
    ["送过来", "sòng guò lái", "sent it over", "hantar ke sini"],
    ["就上班去了", "jiù shàng bān qù le", "and went to work", "dan pergi bekerja"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["噘着嘴", "juē zhe zuǐ", "pouted", "mencebik"],
    ["不说话", "bù shuō huà", "didn't speak", "tidak berkata"],
    ["，", "", "", ""],
    ["奶奶", "nǎi nai", "Grandma", "Nenek"],
    ["说", "shuō", "said", "berkata"],
    ["我", "wǒ", "me", "saya"],
    ["不懂事", "bù dǒng shì", "childish", "tidak memahami"],
    ["，", "", "", ""],
    ["说", "shuō", "said", "berkata"],
    ["凡事", "fán shì", "everything", "segala perkara"],
    ["要讲个", "yào jiǎng ge", "should follow", "perlu ikut"],
    ["先来后到", "xiān lái hòu dào", "first come first served", "siapa datang dulu dapat dulu"],
    ["，", "", "", ""],
    ["自家人", "zì jiā rén", "close ones", "orang sendiri"],
    ["不该", "bù gāi", "should not", "tidak patut"],
    ["和外人", "hé wài rén", "with outsiders", "dengan orang luar"],
    ["“", "", "", ""],
    ["矫情", "jiáo qing", "argue", "bercanggah"],
    ["”", "", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["那么", "nà me", "So", "Maka"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["是", "shì", "was", "ialah"],
    ["大荣姨的", "dà róng yí de", "Da Rong Yi's", "Makcik Da Rong punya"],
    ["“", "", "", ""],
    ["自家人", "zì jiā rén", "close one", "orang sendiri"],
    ["”", "", "", ""],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["是朋友", "shì péng yǒu", "are friends", "ialah kawan"],
    ["。", "", "", ""],
    ["因为", "yīn wèi", "Because", "Kerana"],
    ["是朋友", "shì péng yǒu", "they were friends", "ialah kawan"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["才会", "cái huì", "would", "akan"],
    ["断然", "duàn rán", "firmly", "dengan tegas"],
    ["拒绝", "jù jué", "refuse", "menolak"],
    ["我那", "wǒ nà", "my", "saya punya"],
    ["“", "", "", ""],
    ["走后门", "zǒu hòu mén", "back door", "jalan belakang"],
    ["”", "", "", ""],
    ["式的请求", "shì de qǐng qiú", "request", "permintaan"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["把那只", "bǎ nà zhī", "kept that", "menyimpan itu"],
    ["小网兜", "xiǎo wǎng dōu", "small net bag", "beg jaring kecil"],
    ["保存了", "bǎo cún le", "kept", "simpan"],
    ["很多年", "hěn duō nián", "for many years", "bertahun-tahun"],
    ["，", "", "", ""],
    ["直到", "zhí dào", "until", "sehingga"],
    ["它", "tā", "it", "ia"],
    ["老化得", "lǎo huà de", "aged until", "menjadi tua sehingga"],
    ["又硬又脆", "yòu yìng yòu cuì", "hard and brittle", "keras dan rapuh"],
    ["。", "", "", ""],
    ["虽然", "suī rán", "Although", "Walaupun"],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["地理位置", "dì lǐ wèi zhì", "geographical location", "lokasi geografi"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because of", "kerana"],
    ["局势", "jú shì", "circumstances", "keadaan"],
    ["和其他", "hé qí tā", "and other reasons", "dan lain-lain"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["再也", "zài yě", "never again", "tidak pernah lagi"],
    ["未曾", "wèi céng", "never", "tidak pernah"],
    ["和大荣姨", "hé dà róng yí", "with Da Rong Yi", "dengan Makcik Da Rong"],
    ["见过面", "jiàn guò miàn", "met", "bertemu"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["我们", "wǒ men", "the", "kami"],
    ["共度的", "gòng dù de", "time we spent together", "yang kami lalui bersama"],
    ["美好时光", "měi hǎo shí guāng", "good times", "masa indah"],
    ["却使", "què shǐ", "made me", "membuatkan saya"],
    ["我难以忘怀", "wǒ nán yǐ wàng huái", "unforgettable", "tidak dapat melupakan"],
    ["。", "", "", ""],
    ["什么时候", "shén me shí hou", "When", "Bila"],
    ["能够", "néng gòu", "can", "boleh"],
    ["再次", "zài cì", "again", "lagi"],
    ["听到", "tīng dào", "hear", "mendengar"],
    ["朋友对你说", "péng yǒu duì nǐ shuō", "a friend tell you", "kawan berkata kepada awak"],
    ["“", "", "", ""],
    ["那可不行", "nà kě bù xíng", "That won't do", "Itu tidak boleh"],
    ["”", "", "", ""],
    ["呢", "ne", "", ""],
    ["。", "", "", ""],
    ["敢于", "gǎn yú", "Dare to", "Berani"],
    ["直面", "zhí miàn", "face", "menghadapi"],
    ["你的请求", "nǐ de qǐng qiú", "your request", "permintaan awak"],
    ["并且", "bìng qiě", "and", "dan"],
    ["说", "shuō", "say", "berkata"],
    ["“", "", "", ""],
    ["不行", "bù xíng", "No", "Tidak"],
    ["”", "", "", ""],
    ["的朋友", "de péng yǒu", "friend", "kawan"],
    ["，", "", "", ""],
    ["往往", "wǎng wǎng", "often", "selalu"],
    ["更加", "gèng jiā", "more", "lebih"],
    ["值得我们珍惜", "zhí dé wǒ men zhēn xī", "worthy of our treasure", "patut kita hargai"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["打那以后", "dǎ nà yǐ hòu", "Since then", "Sejak itu"],
    ["，", "", "", ""],
    ["直至", "zhí zhì", "until", "sehingga"],
    ["我", "wǒ", "I", "saya"],
    ["长大成人", "zhǎng dà chéng rén", "grew up", "membesar"],
    ["，", "", "", ""],
    ["便", "biàn", "then", "lalu"],
    ["总是", "zǒng shì", "always", "selalu"],
    ["有意", "yǒu yì", "deliberately", "sengaja"],
    ["躲避", "duǒ bì", "avoid", "mengelakkan"],
    ["那些", "nà xiē", "those", "yang"],
    ["内容空洞的", "nèi róng kōng dòng de", "empty", "kosong"],
    ["“", "", "", ""],
    ["亲热", "qīn rè", "affection", "kemesraan"],
    ["”", "", "", ""],
    ["和", "hé", "and", "dan"],
    ["形态夸张的", "xíng tài kuā zhāng de", "exaggerated", "berlebihan"],
    ["“", "", "", ""],
    ["友好", "yǒu hǎo", "friendship", "persahabatan"],
    ["”", "", "", ""],
    ["。", "", "", ""],
    ["每每觉得", "měi měi jué de", "often feel", "sering terasa"],
    ["，", "", "", ""],
    ["很多人", "hěn duō rén", "many people", "ramai orang"],
    ["在这亲密的", "zài zhè qīn mì de", "in this", "dalam kemesraan ini"],
    ["外壳中", "wài ké zhōng", "shell", "kulit luar"],
    ["，", "", "", ""],
    ["疲惫不堪地", "pí bèi bù kān de", "exhaustedly", "dengan penat"],
    ["劳累着", "láo lèi zhe", "toiling", "berpenat"],
    ["，", "", "", ""],
    ["你敢于", "nǐ gǎn yú", "do you dare", "awak berani"],
    ["为了", "wèi le", "in order to", "untuk"],
    ["说一个真实的", "shuō yí gè zhēn shí de", "say a real", "berkata yang benar"],
    ["“", "", "", ""],
    ["不", "bù", "No", "Tidak"],
    ["”", "", "", ""],
    ["而去破坏", "ér qù pò huài", "to destroy", "untuk merosakkan"],
    ["这种状态吗", "zhè zhǒng zhuàng tài ma", "this state", "keadaan ini"],
    ["？", "", "", ""],
    ["在人们", "zài rén men", "In people's", "Dalam orang ramai"],
    ["小心翼翼的", "xiǎo xīn yì yì de", "cautious", "berhati-hati"],
    ["疲惫中", "pí bèi zhōng", "exhaustion", "kepenatan"],
    ["，", "", "", ""],
    ["远离我们而去的", "yuǎn lí wǒ men ér qù de", "what leaves us", "yang menjauhi kita"],
    ["，", "", "", ""],
    ["恰是", "qià shì", "is precisely", "itulah"],
    ["友谊的真谛", "yǒu yì de zhēn dì", "the true meaning of friendship", "erti persahabatan yang sebenar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    ["现在", "xiàn zài", "Now", "Sekarang"],
    ["，", "", "", ""],
    ["每当我", "měi dāng wǒ", "Whenever I", "Setiap kali saya"],
    ["结识", "jié shi", "make", "berkenalan"],
    ["一个新朋友", "yí gè xīn péng yǒu", "a new friend", "kawan baharu"],
    ["，", "", "", ""],
    ["总是不由自主地", "zǒng shì bù yóu zì zhǔ de", "can't help but", "secara tidak sedar"],
    ["想起", "xiǎng qǐ", "think of", "teringat"],
    ["卖酱油的", "mài jiàng yóu de", "soy sauce seller", "penjual kicap"],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["，", "", "", ""],
    ["只觉得", "zhǐ jué de", "only feel", "hanya rasa"],
    ["能够", "néng gòu", "to be able to", "dapat"],
    ["享受到", "xiǎng shòu dào", "enjoy", "menikmati"],
    ["友人直率的拒绝", "yǒu rén zhí shuài de jù jué", "a friend's straightforward refusal", "penolakan terus terang kawan"],
    ["，", "", "", ""],
    ["实在是", "shí zài shì", "is truly", "sesungguhnya"],
    ["人生一种", "rén shēng yì zhǒng", "a kind of life", "kehidupan sejenis"],
    ["美妙的时光", "měi miào de shí guāng", "wonderful time", "masa yang indah"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["铁凝", "tiě níng", "Tie Ning", "Tie Ning"],
    ["《", "", "", ""],
    ["大荣姨", "dà róng yí", "Da Rong Yi", "Makcik Da Rong"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
